preset: laravel
risky: true
enabled:
  - concat_with_spaces
disabled:
  - concat_without_spaces
  - not_operator_with_successor_space
finder:
  exclude:
    - vendor
  name: "*.php"
  not-path:
    - tests/Stubs